### ISSUE TITLE
How to put null value via SDE

### ISSUE THREAD

**Issue by Muchaszewski** [dvershinin/sde#1]
This issue is pretty simple, how do you insert null, into json via sde?

**Steps:**
1 - `sde Foo null file.json` 

**Result**
```
{
   Foo = "null" <--- notice string paranticies
}
```

**Expected**
```
{
   Foo = null
}
```

There should be syntax to add null into the json, preferably string null should be converted to null object.

**Comment by Muchaszewski** [comment]
I will answer this for someone who might not notice (just as me) that you can omit the value field in sde command.

`sde Foo file.json` will result in `Foo = null`

**Comment by dvershinin** [comment]
Hi @Muchaszewski ,

Thanks for the ticket, but I think prematurely closed.. It didn't have to work that way.

Please check 1.0.0 in that version things are unquoted where they should not be. (booleans, null, digits)
So null will be null.

If "null" (quoted) is required, then pass `-s` option.
