### ISSUE TITLE
Replace json object values in large blobs

### ISSUE THREAD

**Issue by djuloori** [dvershinin/sde#10]
Hey! I have a JSON file that has about 32000 objects. Is there a way that I could find a particular object based on a Key-value and replace it using sde?

Example:

{
  "directDependencies" : [ ],
  "hash" : "358620021da9f373601c1d02581b3fac",
  "name" : "target1"
}

I would want to find the JSON object by the name and replace the hash in the blob.

**Comment by dvershinin** [comment]
@djuloori that's not currently possible and `sde` really is a *simple* editor at this point, so jq is more suitable for this task now
That said, can you elaborate on your json structure? I understand how the objects look like, but the parent structure? These objects are in a array like so maybe?

```json
{
   "objects": [
      {
      "directDependencies" : [ ],
      "hash" : "358620021da9f373601c1d02581b3fac",
      "name" : "target1"
      },
      {
      "directDependencies" : [ ],
      "hash" : "some other hash",
      "name" : "target2"
      }
    ]
}
```

`sde` currently only support setting by index, e.g. `sde objects.1.hash new_value file.json`
