### ISSUE TITLE
Add option to support JSON or YAML-encoded replacement values

### ISSUE THREAD

**Issue by jgarbers** [dvershinin/sde#6]
I have a use case in which I want to set a value to some already-encoded structure. I extract the structure I need from some source using _jq_ or _jp_, and then want to set _that_ as the value under a key in another JSON file using _sde_. I tried that with the current code, but it encodes my replacement JSON data as a single string value. That's completely safe and reasonable behavior, but not what I need in this case.

May I suggest adding an option, perhaps _--value_type=json_ or _--value_type=yaml_, that would treat the value data according to the specified type before updating the target file? This seems sort of like a generalization of your existing _--string_ option, but allowing for other structured interpretations of the provided replacement value.

I've not collaborated on public GItHub projects before but I'd be happy to try this myself and submit a pull request if you're amenable.

Thank you for your consideration and for sharing this work!

**Comment by dvershinin** [comment]
Hi @jgarbers ,

Sure. Pull requests are very welcome.
